import 'package:intl/intl.dart';

import 'package:buzzer_beater/common/preference.dart';
import 'package:buzzer_beater/dao/match.dart';
import 'package:buzzer_beater/dao/period.dart';
import 'package:buzzer_beater/dao/record.dart';
import 'package:buzzer_beater/dao/score.dart';
import 'package:buzzer_beater/dto/match.dart';
import 'package:buzzer_beater/dto/period.dart';
import 'package:buzzer_beater/dto/record.dart';
import 'package:buzzer_beater/dto/result.dart';
import 'package:buzzer_beater/dto/score.dart';
import 'package:buzzer_beater/util/result.dart';

final ApplicationPreference _pref = ApplicationPreference();

Future getSetting(List<Object> _settings) async {
  Future<dynamic> _result = await _pref.getValue(_settings[3], _settings[4]);
  _result ??= _settings[4];
  return _result;
}

dynamic getHomeAway(ResultDto _data, int _side, int _type) {
  dynamic _result;
  switch (_type) {
    case ResultUtil.teamdata:
      _side == ResultUtil.home ? _result = _data.home : _result = _data.away;
      break;
    case ResultUtil.totaldata:
      _side == ResultUtil.home
          ? _result = _data.hometotal
          : _result = _data.awaytotal;
      break;
    case ResultUtil.perioddata:
      _side == ResultUtil.home
          ? _result = _data.homeperiod
          : _result = _data.awayperiod;
      break;
    case ResultUtil.playerdata:
      _side == ResultUtil.home
          ? _result = _data.homeplayers
          : _result = _data.awayplayers;
      break;
    case ResultUtil.progressdata:
      _side == ResultUtil.home
          ? _result = _data.homeprogress
          : _result = _data.awayprogress;
      break;
  }
  return _result;
}

bool isPeriod(List<PeriodDto> _data, int _index) {
  int _sum = 0;
  for (int i = 0; i < _data.length; i++) {
    _sum += _data[i].score;
    if (_sum == _index + 1) {
      return true;
    } else if (_sum > _index) {
      break;
    }
  }
  return false;
}

void test() async {
  MatchDao _mdao = MatchDao();
  MatchDto _mdto = MatchDto();

  var _dateFormat = DateFormat('yyyy年MM月dd日(E) HH:mm', 'ja_JP');
  var _date = _dateFormat.format(DateTime.now());
  _mdto.date = _date;
  _mdto.name = '大会１回戦';
  _mdto.place = '体育館';
  _mdto.coat = 'Aコート';
  _mdto.hometeam = 1;
  _mdto.awayteam = 2;
  _mdto.homeroster = 1;
  _mdto.awayroster = 2;
  _mdto.homeware = 0;
  _mdto.awayware = 1;
  await _mdao.insert(_mdto);

  PeriodDao _pdao = PeriodDao();
  PeriodDto _pdto = PeriodDto();

  _pdto.match = 1;
  _pdto.team = 1;
  _pdto.period = 1;
  _pdto.score = 8;
  _pdto.timeout = 1;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);
  _pdto.period = 2;
  _pdto.score = 6;
  _pdto.timeout = 0;
  _pdto.teamfoul = 2;
  await _pdao.insert(_pdto);
  _pdto.period = 3;
  _pdto.score = 12;
  _pdto.timeout = 1;
  _pdto.teamfoul = 4;
  await _pdao.insert(_pdto);
  _pdto.period = 4;
  _pdto.score = 9;
  _pdto.timeout = 0;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);

  _pdto.match = 1;
  _pdto.team = 2;
  _pdto.period = 1;
  _pdto.score = 12;
  _pdto.timeout = 0;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);
  _pdto.period = 2;
  _pdto.score = 12;
  _pdto.timeout = 0;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);
  _pdto.period = 3;
  _pdto.score = 8;
  _pdto.timeout = 0;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);
  _pdto.period = 4;
  _pdto.score = 7;
  _pdto.timeout = 0;
  _pdto.teamfoul = 0;
  await _pdao.insert(_pdto);

  ScoreDao _sdao = ScoreDao();
  ScoreDto _sdto = ScoreDto();

  _sdto.match = 1;
  _sdto.team = 1;

  _sdto.member = 1;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 2;
  await _sdao.insert(_sdto);
  _sdto.member = 2;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 4;
  await _sdao.insert(_sdto);
  _sdto.member = 0;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 6;
  await _sdao.insert(_sdto);
  _sdto.member = 2;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 8;
  await _sdao.insert(_sdto);

  _sdto.member = 2;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 10;
  await _sdao.insert(_sdto);
  _sdto.member = 2;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 12;
  await _sdao.insert(_sdto);
  _sdto.member = 3;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 14;
  await _sdao.insert(_sdto);

  _sdto.member = 3;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 16;
  await _sdao.insert(_sdto);
  _sdto.member = 1;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 18;
  await _sdao.insert(_sdto);
  _sdto.member = 3;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 20;
  await _sdao.insert(_sdto);
  _sdto.member = 3;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 22;
  await _sdao.insert(_sdto);
  _sdto.member = 1;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 24;
  await _sdao.insert(_sdto);
  _sdto.member = 1;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 26;
  await _sdao.insert(_sdto);

  _sdto.member = 1;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 28;
  await _sdao.insert(_sdto);
  _sdto.member = 2;
  _sdto.period = 4;
  _sdto.point = 1;
  _sdto.score = 29;
  await _sdao.insert(_sdto);
  _sdto.member = 2;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 31;
  await _sdao.insert(_sdto);
  _sdto.member = 3;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 33;
  await _sdao.insert(_sdto);
  _sdto.member = 1;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 35;
  await _sdao.insert(_sdto);

  _sdto.match = 1;
  _sdto.team = 2;

  _sdto.member = 14;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 2;
  await _sdao.insert(_sdto);
  _sdto.member = 14;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 4;
  await _sdao.insert(_sdto);
  _sdto.member = 14;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 6;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 8;
  await _sdao.insert(_sdto);
  _sdto.member = 14;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 10;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 1;
  _sdto.point = 2;
  _sdto.score = 12;
  await _sdao.insert(_sdto);

  _sdto.member = 15;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 14;
  await _sdao.insert(_sdto);
  _sdto.member = 14;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 16;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 18;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 20;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 22;
  await _sdao.insert(_sdto);
  _sdto.member = 14;
  _sdto.period = 2;
  _sdto.point = 2;
  _sdto.score = 24;
  await _sdao.insert(_sdto);

  _sdto.member = 14;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 26;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 28;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 3;
  _sdto.point = 1;
  _sdto.score = 29;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 3;
  _sdto.point = 2;
  _sdto.score = 31;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 3;
  _sdto.point = 1;
  _sdto.score = 32;
  await _sdao.insert(_sdto);

  _sdto.member = 14;
  _sdto.period = 4;
  _sdto.point = 1;
  _sdto.score = 33;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 35;
  await _sdao.insert(_sdto);
  _sdto.member = 15;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 37;
  await _sdao.insert(_sdto);
  _sdto.member = 16;
  _sdto.period = 4;
  _sdto.point = 2;
  _sdto.score = 39;
  await _sdao.insert(_sdto);

  RecordDao _dao = RecordDao();
  RecordDto _dto = RecordDto();

  _dto.team = 1;
  _dto.roster = 1;
  _dto.match = 1;

  _dto.member = 1;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "P'1";
  _dto.foul2 = "U2";
  _dto.foul3 = "T3";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 2;
  _dto.quota1 = 1;
  _dto.quota2 = 0;
  _dto.quota3 = 2;
  _dto.quota4 = 0;
  _dto.foul1 = "P'1";
  _dto.foul2 = "U2";
  _dto.foul3 = "T3";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 3;
  _dto.quota1 = 0;
  _dto.quota2 = 1;
  _dto.quota3 = 0;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 4;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 5;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 6;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 7;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 8;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 9;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 10;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);

  _dto.team = 2;
  _dto.roster = 2;
  _dto.match = 1;

  _dto.member = 11;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 12;
  _dto.quota1 = 1;
  _dto.quota2 = 0;
  _dto.quota3 = 1;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 13;
  _dto.quota1 = 0;
  _dto.quota2 = 1;
  _dto.quota3 = 0;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 14;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 15;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 16;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 17;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 18;
  _dto.quota1 = 1;
  _dto.quota2 = 1;
  _dto.quota3 = 1;
  _dto.quota4 = 1;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 19;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
  _dto.member = 20;
  _dto.quota1 = 0;
  _dto.quota2 = 0;
  _dto.quota3 = 0;
  _dto.quota4 = 0;
  _dto.foul1 = "";
  _dto.foul2 = "";
  _dto.foul3 = "";
  _dto.foul4 = "";
  _dto.foul5 = "";
  await _dao.insert(_dto);
}
